version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec
    - errorlint
    - bodyclose
  settings:
    gosec:
      excludes:
        - G115  # integer overflow conversions — file sizes are always non-negative
        - G301  # directory permissions — test dirs don't need restrictive perms
        - G304  # file inclusion via variable — CLI tool that opens user-specified files by design
        - G306  # WriteFile permissions — test files don't need restrictive perms
        - G401  # weak crypto primitives — MD5/SHA-1 are intentional for VirusTotal compatibility
        - G404  # weak random — jitter doesn't need crypto-grade randomness
        - G501  # blocklisted import crypto/md5 — required for VirusTotal hash lookups
        - G505  # blocklisted import crypto/sha1 — required for VirusTotal hash lookups
